services:
  client:
    build: ./client
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
  agent:
    build: ./agent
    env_file: .env
    volumes:
      - ./agent:/app
